#!/bin/sh
b=$(basename $1 .c)
echo  $b":"
fcc -X -m8080 -c tests/$b.c
ld85 -b -C0 testcrt0.o tests/$b.o -o tests/$b /opt/fcc/lib/8080/lib8080.a -m tests/$b.map
./emu85 -d tests/$b tests/$b.map 2> $b.log
