#!/bin/sh
b=$(basename $1 .c)
echo  $b":"
fcc -O2 -mnova3 -X -c tests/$b.c
ldnova -b -C512 -Z80 testcrt0_nova3.o tests/$b.o -o tests/$b /opt/fcc/lib/nova/libnova3.a -m tests/$b.map
./nova -d tests/$b tests/$b.map 2> $b.log
