#!/bin/sh
b=$(basename $1 .c)
echo  $b":"
fcc -m6303 -O -X -c tests/$b.c
ld6800 -b -Z64 -C256 testcrt0_6303.o tests/$b.o -o tests/$b /opt/fcc/lib/6303/lib6303.a
./emu6800 -d 6303 tests/$b tests/$b.map 2> $b.log
