#!/bin/sh
b=$(basename $1 .c)
echo  $b":"
fcc -mtms7000 -X -c tests/$b.c
ld7000 -b -C0x200 -m tests/$b.map testcrt0_tms7000.o tests/$b.o -o tests/$b /opt/fcc/lib/tms7000/libtms7000.a
./emu7k -d tests/$b tests/$b.map 2> $b.log
