#!/bin/sh

if [ "$#" -ne 1 ]
then echo "Usage: $0 c_file"; exit 1
fi

# Make cprintf.o
fcc -m6800 -O -c cprintf.c

b=$(basename $1 .c)
echo "$1:"
fcc -m6800 -O -c $b.c

ld6800 -v -b -C256 -Z0 -m $b.map -o $b ../testcrt0_6800.o cprintf.o $b.o /opt/fcc/lib/6800/lib6800.a  /opt/fcc/lib/6800/libc.a
../emu6800 6800 $b $b.map 2> $b.log
#rm -f $b.o $b $b.map 
fcc -m6800 -O -S $b.c
